"theme-bootstrap-2" :
  "use" : "theme"

posts :
  sort: [ "date", "desc" ]
  rss:
    enable: true # set to false to disable rss
    limit: 30   # default is 20

production_url: 'http://engineering.mydrivesolutions.com'

analytics:
  provider: google
  google:
    tracking_id: 'UA-32835100-1'
