"theme-bootstrap-2" :
  "use" : "theme"

posts :
  sort: [ "date", "desc" ]
  rss:
    enable: true # set to false to disable rss
    limit: 30   # default is 20

production_url: 'http://engineering.mydrivesolutions.com'

widgets :
  analytics :
    use : google
    tracking_id : 'UA-32835100-1'

authors:
  gavin:
    name : Gavin Heavyside
    twitter : gavinheavyside
    bio  : Director of Engineering at MyDrive
  carlos:
    name : Carlos Alonso Perez
    twitter : calonso
    bio  : Software Engineer
  william:
    name : William Michael Fish
    twitter : wfishcouk
    bio: Software Engineer
